### ISSUE TITLE
ArgumentError: Error #3500: The extension context does not have a method with the name init.

### ISSUE THREAD

**Issue by Brujotesco** [tuarua/Battery-ANE#19]
**ArgumentError: Error # 3500: The extension context does not have a method with the name init.**

I don't know why I get that error, I read everything and followed the steps but it throws me that error even though I put try {} catch, install the dependencies, I don't know what I'm doing wrong.

AIR SDK Ver. 33.1.1.406

PS: I am using google translate

**Comment by tuarua** [comment]
You need to provide more info.

Are you building an Android app or iOS app?
Have you run the sample project included with the repo?
You are likely missing frekotlin or gson ANEs

See extensions section
https://github.com/tuarua/Battery-ANE/blob/master/example/src/Main-app.xml#L26

**Comment by Brujotesco** [comment]
Thank you for answering me, I let the example you put fly, I also realize I do not know if it is just me but the BatteryANE.ane extension that is downloaded from the dependency does not make it compile, I use animate cc 2021 because with IntelliJ told me that the content of .swf did not exist at the time of compiling, despite deleting the manifes.xml, it recreated it.

so that this error does not appear, it would be good to add a variable of whether it supports (battery.supportDevice) something like that.

I'm using:
windows 10
Animate CC 2021
Air SDK 33.1.1.406
Compiling for Android

Also mention that it takes care of the other two ane in case a new project is started, I still do not understand well what they are for! but I suppose they serve to make the others work, if I'm wrong, correct myself.

Thanks

**Comment by tuarua** [comment]
https://github.com/tuarua/Battery-ANE/releases/download/1.7.0/BatteryANE.ane?raw=true
https://github.com/tuarua/Android-ANE-Dependencies/blob/master/anes/misc/com.google.code.gson.gson-2.8.6.ane?raw=true
https://github.com/tuarua/Android-ANE-Dependencies/blob/master/anes/kotlin/com.tuarua.frekotlin-1.42.0.ane?raw=true
