### ISSUE TITLE
Getting an Error on an Android device and PC Debugger.

### ISSUE THREAD

**Issue by alwinlubbers** [tuarua/Battery-ANE#3]
I'm getting an Error when using your ANE.

Error #3500: The extension context does not have a method with the name init.
I'm using the latest version (0.3) from the 'Releases' section.

Thanks in advance.

**Comment by alwinlubbers** [comment]
This is a section from my app-xml

`<android>
        <manifestAdditions><![CDATA[<manifest>
        <extensions>
<extensionID>com.tuarua.frekotlin</extensionID>
<extensionID>com.google.code.gson.gson</extensionID>
<extensionID>com.tuarua.BatteryANE</extensionID>
</extensions>
        <uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />

<application>
    <service android:name="com.doitflash.speech.speechToText.SpeechRecognitionService">
</service>
</application>
</manifest>]]></manifestAdditions>
    </android>
`

**Comment by alwinlubbers** [comment]
section of the code:

`var battery:BatteryANE = BatteryANE.battery;
	battery.addEventListener(BatteryEvent.ON_CHANGE, onBatteryChange);
	battery.addEventListener(StateEvent.ON_CHANGE, onStateChange);`

**Comment by tuarua** [comment]
Did you run the example included with the project?

Did you read the readme section about running the get_dependencies script?

You also need to have the 2 following ANEs
com.tuarua.frekotlin.ane
com.google.code.gson.gson-2.8.1.ane

https://github.com/tuarua/Android-ANE-Dependencies/blob/master/anes/kotlin/com.tuarua.frekotlin.ane?raw=true

https://github.com/tuarua/Android-ANE-Dependencies/blob/master/anes/misc/com.google.code.gson.gson-2.8.1.ane?raw=true

**Comment by tuarua** [comment]
Also, If you run the code on Desktop you should surround with a try catch block, because naturally there is no such thing as Battery checking on desktop.

try{ 
}catch(){
}

**Comment by alwinlubbers** [comment]
Thank you so much. Works like a charm!
